package queue

import "time"

// Message is the fundamental unit of data in the queue.
// It is immutable once published — consumers receive a copy.
type Message struct {
	// ID uniquely identifies this message within its topic.
	// Generated by the broker at publish time.
	ID string

	// Topic is the named channel this message belongs to.
	Topic string

	// Payload is the raw bytes of the message body.
	// The broker treats this as opaque — encoding is the caller's concern.
	Payload []byte

	// Attempts tracks how many delivery attempts have been made.
	// Zero on first delivery. Incremented on each retry.
	Attempts int

	// Timestamp is when the message was first published to the broker.
	Timestamp time.Time
}
